version: '3'

services:
  postgres:
    image: postgres:11.7
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"

  ingryd:
    build: .
    environment:
      - DB_NAME=test
      - DB_USER=test
      - DB_HOST=postgres
      - DB_PASS=test
      - LOG_LEVEL
      - LOG_CONSOLE
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    volumes:
      - .:/app
